---
apiVersion: v1
kind: Service
metadata:
  name: infisical-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: infisical-service.os-framework.svc.cluster.local
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

