# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: settings-nft
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: nft
#   deployment: settings
#   description: Get Cloud Bind NFT List
#   endpoint: settings-service.{{ .Release.Namespace }}
#   group: service.settings
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   opApis:
#     - name: getNFTAddress
#       uri: /api/cloud/getNFTAddress
#   version: v1
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: settings-account
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: account
#   deployment: settings
#   description: Get Acccount saved in Settings
#   endpoint: settings-service.{{ .Release.Namespace }}
#   group: service.settings
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   opApis:
#     - name: getAccount
#       uri: /api/account
#   version: v1
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: settings-backup-password
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: backupPassword
#   deployment: settings
#   description: Get Backup Plan's Password
#   endpoint: settings-service.{{ .Release.Namespace }}
#   group: service.settings
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   opApis:
#     - name: getAccount
#       uri: /api/backup/password
#   version: v1
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: settings-account-retrieve
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: legacy_api
#   deployment: settings
#   description: settings account retrieve legacy api
#   endpoint: settings-service.{{ .Release.Namespace }}
#   group: service.settings
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   version: v1
#   opApis:
#     - name: POST
#       uri: /api/account/retrieve
#     - name: GET
#       uri: /api/account/all
#     - name: POST
#       uri: /api/cookie/retrieve
#     - name: POST
#       uri: /api/cookie
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: intent-api
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: legacy_api
#   deployment: edge-desktop
#   description: edge-desktop legacy api
#   endpoint: edge-desktop.{{ .Release.Namespace }}
#   group: api.intent
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   version: v1
#   opApis:
#   - name: POST
#     uri: /server/intent/send
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: intent-api-v2
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: legacy_api
#   deployment: edge-desktop
#   description: edge-desktop legacy api
#   endpoint: edge-desktop.{{ .Release.Namespace }}
#   group: api.intent
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   version: v2
#   opApis:
#     - name: POST
#       uri: /server/intent/send
# status:
#   state: active

# ---
# apiVersion: sys.bytetrade.io/v1alpha1
# kind: ProviderRegistry
# metadata:
#   name: destktop-ai-provider
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   dataType: ai_message
#   deployment: edge-desktop
#   description: search ai callback
#   endpoint: edge-desktop.{{ .Release.Namespace }}
#   group: service.desktop
#   kind: provider
#   namespace: {{ .Release.Namespace }}
#   opApis:
#   - name: AIMessage
#     uri: /server/ai_message
#   version: v1
# status:
#   state: active

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:settings-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/settings
    provider-service-ref: settings-service.{{ .Release.Namespace }}
rules:
- nonResourceURLs: 
  - "/api/cloud/getNFTAddress"
  - "/api/account/"
  - "/api/backup/password"
  - "/api/account/retrieve"
  - "/api/account/all"
  - "/api/cookie/retrieve"
  - "/api/cookie/"
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:edge-desktop-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/edge-desktop
    provider-service-ref: edge-desktop.{{ .Release.Namespace }}
rules:
- nonResourceURLs: 
  - "/server/intent/send"
  - "/server/ai_message"
  verbs: ["*"]  