

{{ $userspace_pv_rootpath := printf "%s%s" .Values.rootPath "/rootfs/userspace" }}
{{ $appcache_pv_rootpath := printf "%s%s" .Values.rootPath "/userdata/Cache" }}
{{ $dbdata_pv_rootpath := printf "%s%s" .Values.rootPath "/userdata/dbdata" }}

{{ $userspace_rand16 := randAlphaNum 16 | lower }}
{{ if .Values.bfl.userspace_rand16 }}
{{ $userspace_rand16 = .Values.bfl.userspace_rand16 }}
{{ end }}
{{ $userspace_pv := printf "pv-userspace-%s-%s" .Values.bfl.username $userspace_rand16 }}
{{ $userspace_pvc := printf "pvc-userspace-%s-%s" .Values.bfl.username $userspace_rand16 }}
{{ $userspace_sc := printf "juicefs-localpath-userspace-%s" .Values.bfl.username -}}
{{ $userspace_storage := "50Gi" -}}

{{ $appcache_rand16 := randAlphaNum 16 | lower }}
{{ if .Values.bfl.appcache_rand16 }}
{{ $appcache_rand16 = .Values.bfl.appcache_rand16 }}
{{ end }}
{{ $appcache_pv := printf "pv-appcache-%s-%s" .Values.bfl.username $appcache_rand16 }}
{{ $appcache_pvc := printf "pvc-appcache-%s-%s" .Values.bfl.username $appcache_rand16 }}
{{ $appcache_sc := printf "hostpath-appcache-%s" .Values.bfl.username }}
{{ $appcache_storage := "50Gi" -}}

{{ $dbdata_rand16 := randAlphaNum 16 | lower }}
{{ if .Values.bfl.dbdata_rand16 }}
{{ $dbdata_rand16 = .Values.bfl.dbdata_rand16 }}
{{ end }}
{{ $dbdata_pv := printf "pv-dbdata-%s-%s" .Values.bfl.username $dbdata_rand16 }}
{{ $dbdata_pvc := printf "pvc-dbdata-%s-%s" .Values.bfl.username $dbdata_rand16 }}
{{ $dbdata_sc := printf "hostpath-dbdata-%s" .Values.bfl.username }}
{{ $dbdata_storage := "80Gi" -}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default $userspace_pv .Values.bfl.userspace_pv }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ $userspace_storage }}
  hostPath:
    path: '{{ $userspace_pv_rootpath }}/{{ default $userspace_pvc .Values.bfl.userspace_pvc }}'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: {{ default $userspace_sc .Values.bfl.userspace_sc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default $userspace_pvc .Values.bfl.userspace_pvc }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '{{ $userspace_storage }}'
  volumeMode: Filesystem
  {{ if .Values.bfl.userspace_pv }}
  volumeName: {{ .Values.bfl.userspace_pv }}
  {{ end }}
  storageClassName: {{ default $userspace_sc .Values.bfl.userspace_sc }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default $appcache_pv .Values.bfl.appcache_pv }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ $appcache_storage }}
  hostPath:
    path: '{{ $appcache_pv_rootpath }}/{{ default $appcache_pvc .Values.bfl.appcache_pvc }}'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: {{ default $appcache_sc .Values.bfl.appcache_sc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default $appcache_pvc .Values.bfl.appcache_pvc }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $appcache_storage }}
  volumeMode: Filesystem
  {{ if .Values.bfl.appcache_pv }}
  volumeName: {{ .Values.bfl.appcache_pv }}
  {{ end }}
  storageClassName: {{ default $appcache_sc .Values.bfl.appcache_sc }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default $dbdata_pv .Values.bfl.dbdata_pv }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ $dbdata_storage }}
  hostPath:
    path: '{{ $dbdata_pv_rootpath }}/{{ default $dbdata_pvc .Values.bfl.dbdata_pvc }}'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: {{ default $dbdata_sc .Values.bfl.dbdata_sc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default $dbdata_pvc .Values.bfl.dbdata_pvc }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $dbdata_storage }}
  {{ if .Values.bfl.dbdata_pv }}
  volumeName: {{ .Values.bfl.dbdata_pv }}
  {{ end }}
  volumeMode: Filesystem
  storageClassName: {{ default $dbdata_sc .Values.bfl.dbdata_sc }}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bytetrade-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:bytetrade-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bytetrade-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bfl
  namespace: {{ .Release.Namespace }}
  labels:
    tier: bfl
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    username: '{{ .Values.bfl.username }}'
    userspace_rand16: {{ default $userspace_rand16 .Values.bfl.userspace_rand16 }}
    userspace_pv: {{ default $userspace_pv .Values.bfl.userspace_pv }}
    userspace_pvc: {{ default $userspace_pvc .Values.bfl.userspace_pvc }}
    userspace_sc: {{ default $userspace_sc .Values.bfl.userspace_sc }}
    userspace_hostpath: '{{ $userspace_pv_rootpath }}/{{ default $userspace_pvc .Values.bfl.userspace_pvc }}'
    userspace_storage: {{ $userspace_storage }}

    appcache_rand16: {{ default $appcache_rand16 .Values.bfl.appcache_rand16 }}
    appcache_pv: {{ default $appcache_pv .Values.bfl.appcache_pv }}
    appcache_pvc: {{ default $appcache_pvc .Values.bfl.appcache_pvc }}
    appcache_sc: {{ default $appcache_sc .Values.bfl.appcache_sc }}
    appcache_hostpath: '{{ $appcache_pv_rootpath }}/{{ default $appcache_pvc .Values.bfl.appcache_pvc }}'
    appcache_storage: {{ $appcache_storage }}

    dbdata_rand16: {{ default $dbdata_rand16 .Values.bfl.dbdata_rand16 }}
    dbdata_pv: {{ default $dbdata_pv .Values.bfl.dbdata_pv }}
    dbdata_pvc: {{ default $dbdata_pvc .Values.bfl.dbdata_pvc }}
    dbdata_sc: {{ default $dbdata_sc .Values.bfl.dbdata_sc }}
    dbdata_hostpath: '{{ $dbdata_pv_rootpath }}/{{ default $dbdata_pvc .Values.bfl.dbdata_pvc }}'
    dbdata_storage: {{ $dbdata_storage }}
spec:
  serviceName: bfl
  replicas: 1
  selector:
    matchLabels:
      tier: bfl
  template:
    metadata:
      labels:
        tier: bfl
      annotations:
{{ if .Values.telemetry }}
        instrumentation.opentelemetry.io/inject-go: "olares-instrumentation"
        instrumentation.opentelemetry.io/go-container-names: "api"    
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/bfl-api"
        instrumentation.opentelemetry.io/inject-nginx: "olares-instrumentation"
        instrumentation.opentelemetry.io/inject-nginx-container-names: "ingress"    
{{ end }}
    spec:
{{ if .Values.bfl.admin_user }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: node-role.kubernetes.io/master
                operator: Exists
            weight: 10
{{ end }}            
      serviceAccountName: bytetrade-controller
      priorityClassName: "system-cluster-critical"
      initContainers:
      - name: init-userspace
        image: busybox:1.28
        volumeMounts:
        - name: userspace-dir
          mountPath: /userspace
        - name: appcache-dir
          mountPath: /appdata
        - name: dbdata-dir
          mountPath: /dbdata
        command:
        - sh
        - -c
        - |
          init=$(test -d /userspace/Home; echo $?) && \
          mkdir -p /userspace/Home/Documents && \
          mkdir -p /userspace/Home/Downloads && \
          mkdir -p /userspace/Home/Pictures && \
          mkdir -p /userspace/Home/Movies && \
          mkdir -p /userspace/Home/Music && \
          mkdir -p /userspace/Home/Code && \
          mkdir -p /userspace/Data; \
          if [ $init -ne 0 ]; then \
          chown -R 1000:1000 /userspace/Home && \
          chown -R 1000:1000 /userspace/Data && \
          chown -R 1000:1000 /appdata; \
          fi 
      - name: setsysctl
        image: 'busybox:1.28'
        command:
          - sh
          - '-c'
          - |
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.ipv4.ip_local_port_range="1024 65535"
            sysctl -w net.ipv4.tcp_tw_reuse=1
            sysctl -w fs.file-max=1048576
        securityContext:
          privileged: true

      containers:
      - name: api
        image: beclab/bfl:v0.4.28
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - name: userspace-dir
          mountPath: /userspace
        - name: appcache-dir
          mountPath: /appdata
        command:
        - /bfl-api
        - -u
        - '{{ .Values.bfl.username }}'
        - --log-level
        - debug
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 3
          tcpSocket:
            port: 8080
        env:
        - name: APP_SERVICE_SERVICE_HOST
          value: app-service.user-system-{{ .Values.bfl.username }}
        - name: APP_SERVICE_SERVICE_PORT
          value: '28080'
        - name: USER_DEFAULT_MEMORY_LIMIT
          value: '3G'
        - name: USER_DEFAULT_CPU_LIMIT
          value: '1000m'
        - name: BFL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BACKUP_SERVER
          value: backup-server.os-framework:8082
        - name: L4_PROXY_IMAGE_VERSION
          value: v0.3.4
        - name: L4_PROXY_SERVICE_ACCOUNT
          value: os-network-internal
        - name: L4_PROXY_NAMESPACE
          value: os-network
        - name: REVERSE_PROXY_AGENT_IMAGE_VERSION
          value: v0.1.10
        - name: TERMINUS_CERT_SERVICE_API
          value: {{ .Values.bfl.terminus_cert_service_api }}
        - name: TERMINUS_DNS_SERVICE_API
          value: {{ .Values.bfl.terminus_dns_service_api }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      - name: ingress
        image: beclab/bfl-ingress:v0.3.18
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ngxlog
          mountPath: /var/log/nginx
        command:
        - /bfl-ingress
        - -user
        - '{{ .Values.bfl.username }}'
        - -enable-nginx
        - -bfl-svc
        - bfl
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 10
          terminationGracePeriodSeconds: 3
          httpGet:
            port: 8082
            path: /healthz
            scheme: HTTP
      volumes:
      - name: ngxlog
        emptyDir: {}
      - name: userspace-dir
        persistentVolumeClaim:
          claimName: {{ default $userspace_pvc .Values.bfl.userspace_pvc }}
      - name: appcache-dir
        persistentVolumeClaim:
          claimName: {{ default $appcache_pvc .Values.bfl.appcache_pvc }}
      - name: dbdata-dir
        persistentVolumeClaim:
          claimName: {{ default $dbdata_pvc .Values.bfl.dbdata_pvc }}

---
apiVersion: v1
kind: Service
metadata:
  name: bfl
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: ingress-http
    port: 1080
    targetPort: 80
    protocol: TCP
  - name: ingress-https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    tier: bfl


