
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: olares-instrumentation
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  exporter:
    endpoint: https://jaeger-storage-instance-collector.os-platform:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.53.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  nginx:
    image: bytetrade/autoinstrumentation-apache-httpd:1.0.4-fix3
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.20.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
    resourceRequirements:
      limits:
        memory: 256Mi

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: olares-instrumentation
  namespace: user-system-{{ .Values.bfl.username }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"

spec:
  exporter:
    endpoint: https://jaeger-storage-instance-collector.os-platform:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.53.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  nginx:
    image: bytetrade/autoinstrumentation-apache-httpd:1.0.4-fix3
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/json
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.20.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-platform:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "1.0"
    resourceRequirements:
      limits:
        memory: 256Mi

