DROP TABLE IF EXISTS install_config;
DROP TABLE IF EXISTS install_logs;

CREATE TABLE IF NOT EXISTS install_config (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    terminus_os_domainname VARCHAR(120) NOT NULL,
    terminus_os_username VARCHAR(50) NOT NULL,
    kube_type VARCHAR(10) NOT NULL,
    vendor VARCHAR(20) NOT NULL,
    gpu_enable INTEGER NOT NULL DEFAULT 0,
    gpu_share INTEGER NOT NULL DEFAULT 0,
    version VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS install_logs (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    message VARCHAR(512) NOT NULL,
    state VARCHAR(100) NOT NULL,
    percent INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);